### Create new user
POST http://localhost:3050/api/auth/register
Content-Type: application/json

{
  "name"        : "Dwi Prasetyo",
  "email"       : "dwi@example.com",
  "username"    : "dwi",
  "password"    : "1"
}

### Login to get token
POST http://localhost:3050/api/auth/login
Content-Type: application/json

{
  "email"       : "dwi@example.com",
  "password"    : "1"
}

### Get Profile
GET http://localhost:3050/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR3aUBleGFtcGxlLmNvbSIsImV4cCI6MTc3MjYzMzczMiwiaWQiOjEsInJvbGUiOiIiLCJzdG9yZSI6IiJ9.xN2J7Z6j2wh-X_tYfYqlBXlPqFkdjO7Z8hPCMwJi1iY


### Create Store
POST http://localhost:3050/api/stores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR3aUBleGFtcGxlLmNvbSIsImV4cCI6MTc3MjYzMzczMiwiaWQiOjEsInJvbGUiOiIiLCJzdG9yZSI6IiJ9.xN2J7Z6j2wh-X_tYfYqlBXlPqFkdjO7Z8hPCMwJi1iY
Content-Type: application/json

{
  "code": "store-099",
  "name": "Store 099",
  "email": "store099@example.com"
}